[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std=lib/forge-std/src"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 20000
fuzz_runs = 500
max_test_rejects = 100000

[profile.ci]
inherits = "default"
verbosity = 4
