# ✅ Solidity CI/CD Toolkit for Your Project

This setup gives you:
1. 📛 A README badge to show CI status
2. 🚀 A GitHub Actions CD pipeline to deploy on version tag
3. 🧰 A local `Makefile` to match CI (run tests, slither, solhint, etc)

---

## 1. 📛 Add CI Badge to Your `README.md`
Paste this at the **top** of your `README.md`:

```markdown
![Solidity CI](https://github.com/s0xattakdefand/attack-Defend/actions/workflows/solidity-ci.yml/badge.svg)
```

> ✅ This updates automatically with each push or PR.

---

## 2. 🚀 Add CD Pipeline for Contract Deployment
Create this file:
```bash
.github/workflows/solidity-cd.yml
```

```yaml
name: Solidity CD

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on version tags like v1.2.3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Deploy Contract
        run: forge script script/DeployMainnet.s.sol \
            --rpc-url ${{ secrets.MAINNET_RPC }} \
            --private-key ${{ secrets.DEPLOY_KEY }} \
            --broadcast
        env:
          FOUNDRY_PROFILE: ci

      - name: Verify on Etherscan
        run: forge verify-contract --chain-id 1 \
            --etherscan-api-key ${{ secrets.ETHERSCAN_API_KEY }} \
            <your_contract_address> <ContractName>
```

> Make sure to set these in GitHub Secrets:
> - `MAINNET_RPC`
> - `DEPLOY_KEY`
> - `ETHERSCAN_API_KEY`

---

## 3. 🧰 `Makefile` to Mirror CI
Create a file in your root:
```bash
Makefile
```

```makefile
.PHONY: fmt lint test gas slither check all

fmt:
	forge fmt

lint:
	solhint '{A,B,C,...,Z,src}/**/*.sol'

slither:
	slither src/ basicFoundryNoted/fundMeAgain/src/ || true

test:
	FOUNDRY_PROFILE=ci forge test

gas:
	FOUNDRY_PROFILE=ci forge test --gas-report

check: fmt lint test slither

all: check gas
```

> ✅ Run everything just like GitHub Actions:
```bash
make all
```

---

Let me know if you'd like to add:
- 📦 Auto `npm version` + tag
- 🔒 Safe testnets for staging deployment
- 📊 Gas report diffs on PRs
